channels:
- conda-forge
dependencies:
- coveralls
- coverage
- codacy-coverage
- pyiron_base=0.5.12
- matplotlib=3.5.2
- temmeta=0.0.6
- pystem=0.0.26
- match-series
- hyperspy=1.7.0
- scanf
- numpy=1.22.3
