channels:
- conda-forge
dependencies:
- pyiron_base=0.2.19    # simulation framework
- matplotlib=3.4.2      # plotting library
- temmeta=0.0.6         # TEM image post processing
- pystem =0.0.25        # image segmentation
- match-series          # ridge deformation 
- hyperspy=1.6.4        # spectroscopy
- scanf                 # file path utility 
- papermill             # execute notebooks 
